### ISSUE TITLE
Rebase your branches, not merge please.

### ISSUE THREAD

**Issue by xiangxw** [xiangxw/mupdf-qt#2]
@Code-ReaQtor 

I removed pdf_files from the repository beacause these files may be sensitive.
You should use git rebase on your own branches, not merge.

see also: https://help.github.com/articles/remove-sensitive-data#dealing-with-collaborators

Or you can just clone a new one if it's ok. Sorry for this.

**Comment by xiangxw** [comment]
I removed pdf_files(big size) from the repository, but these files exists on GitHub.
I know how to purge these files on my local repository, but I don't know how to do it with the remote repository on GitHub. When I clone a new local repository, the repository size is still huge. Can anyone help?

**Comment by roniemartinez** [comment]
sorry, I don't know how to use "git rebase". I am using the git client from
github. can you guide me?

**Comment by xiangxw** [comment]
you can just delete you local repository and clone a new one.
sorry for such a trouble.

At 2013-05-31 15:29:38,"Ronie Martinez" notifications@github.com wrote:
sorry, I don't know how to use "git rebase". I am using the git client from
github. can you guide me?

**Comment by roniemartinez** [comment]
Thanks, it is OK now.
