### ISSUE TITLE
Load from QByteArray

### ISSUE THREAD

**Issue by roniemartinez** [xiangxw/mupdf-qt#3]
I came across a problem (http://qt-project.org/forums/viewthread/29427/) about loading pdf from QByteArray. @xiangxw, I can't find a solution for this... I wonder if this is possible?

**Comment by xiangxw** [comment]
you mean loading pdf from QByteArray or converting from QByteArray to QPainter?

**Comment by roniemartinez** [comment]
Just the "pdf from QByteArray"

**Comment by xiangxw** [comment]
1. use `char * QByteArray::data()` or `const char * QByteArray::constData() const` to get raw data.
2. use `fz_stream *fz_open_memory(fz_context *ctx, unsigned char *data, int len)` to get a `fz_stream`.
3. use `fz_document *fz_open_document_with_stream(fz_context *ctx, const char *magic, fz_stream *stream)` to get a `fz_document`.
4. done.

see also QByteArray and fitz.h
I don't know whether it works or not. ^_^

**Comment by xiangxw** [comment]
Fixed by @qkdreyer with #12
