### ISSUE TITLE
MuPDF version requirements question.

### ISSUE THREAD

**Issue by vitalivanov** [xiangxw/mupdf-qt#4]
Hi,

On compile mupdf-qt wiki page:
https://github.com/xiangxw/mupdf-qt/wiki/Compile-libmupdf-qt

.. it's written that we should have the following file set present:
include/fitz.h
include/fitz-internal.h
include/memento.h
include/mupdf.h
include/mupdf-internal.h
include/mucbz.h
include/muxps.h
include/muxps-internal.h

If you would download and compile latest mupdf from:
git clone git://git.ghostscript.com/mupdf.git
You will not have many of those.

What are the mupdf version dependencies?
I was not able to find this info anywhere. Sorry.
Is there any plans to support latest mupdf?

**Comment by roniemartinez** [comment]
Hi, those files are all in the source code of muPDF (https://code.google.com/p/mupdf/downloads/list). They are different folders (you might want to look for them, again). It was just to make it organized that the author created an "include" folder and copied all those header files.

**Comment by vitalivanov** [comment]
Sorry, I was not clear.

I'm talking about dependency of mupdf-qt to *internal.h files like:
include/fitz-internal.h
include/muxps-internal.h

These files are not available in latest mupdf anymore.
New version was uploaded a few hours ago btw:
https://mupdf.googlecode.com/files/mupdf-1.3-source.tar.gz

After untarring it:
$ find ./mupdf-1.3-source -name *internal.h
./mupdf-1.3-source/thirdparty/freetype/include/freetype/internal/internal.h
./mupdf-1.3-source/thirdparty/openjpeg/thirdparty/liblcms2/src/lcms2_internal.h
$

These files were merged to their common version in commit:
http://git.ghostscript.com/?p=mupdf.git;a=commit;h=8856f8521a42872a95579666b24ecfb65c5a20a1

So what is the status of mupdf-qt and latest mupdf?

**Comment by roniemartinez** [comment]
Oh, I see that there was a new  version of MuPDF (sorry my bad)... The new version is not supported by mupdf-qt yet. We will see if we can allocate time for that.

**Comment by xiangxw** [comment]
The latest development branch of mupdf-qt will clone mupdf (version 1.5 nowadays) automatically using the following command

```
git clone https://github.com/xiangxw/mupdf-qt.git
cd mupdf-qt
git submodule update --init --recursive
```

see the compile guide: https://github.com/xiangxw/mupdf-qt/blob/dev/README.md
