### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by sebblonline** [xiangxw/mupdf-qt#5]
Hi,

I am using your Qt wrapper, which really works fine in general. Great work.
But I notice some memory leaks which can be reproduced with the simpleviewer example you provide with the wrapper. When opening a PDF document repeatedly (and maybe moving through pages) the used memory increases in the task manager / resource monitor of Windows 7. 
I compared with the pure win32 example provided with the mupdf lib itself an couldn't find leaks there.

regards

**Comment by xiangxw** [comment]
I can't reproduce your problem, may be you are using the 'master' branch.
Please test the 'dev' branch. Thanks

**Comment by sebblonline** [comment]
I am using the dev branch and also had these problems with the dev branch.

**Comment by xiangxw** [comment]
Could you please attach your executable file and I'll try to find the problem.

**Comment by sebblonline** [comment]
I wrote an email to you, because I dont know how to add files here in github. Is that possible anyway?

**Comment by xiangxw** [comment]
may be you can add a link here(dropdox, ubuntu one, etc.)

**Comment by sebblonline** [comment]
https://dl.dropboxusercontent.com/u/2748349/mupdf-qt_example.zip
(updated, use 2nd version, if visible at all)

**Comment by xiangxw** [comment]
thanks, I'll try to find the problem.

**Comment by sebblonline** [comment]
got it. 
In mupdf-page.cpp, line 136 you reinitialize a new *dev but never delete it. You just created a fz_device pointer before the fz_try() block, which you check for NULL afterwards. The fz_device inside is never deleted.

**Comment by xiangxw** [comment]
Yes, thanks a lot!
Fixed.
